algoritmo "somaparamentroreferencial"
// Função :
// Autor :
// Data : 04/11/2020
// Seção de Declarações 
var
    x,y:inteiro
    procedimento  soma(var a,b:inteiro)
    inicio
    a<-a+1
    b<-b+2
    escreval ("valores de a =",a)
    escreval("valores de b =",a)
    escreval ("valores de a+b =",a+b)
    fimprocedimento
inicio
x<-4
y<-8
soma(x,y)
escreval("o valor de x =",x)
escreval("o valore de y =",y)
fimalgoritmo
