algoritmo "fiboncci"
// Função :
// Autor :
// Data : 04/11/2020
// Seção de Declarações 
var
  c,t1,t2,t3:inteiro
  proximofibonacci:caracter
  procedimento  proxmofibonacci(var a,b:inteiro)
  var c: inteiro
  inicio
    c:=a+b
    escreval(c)
    a:=B
    b:=c
  
  fimprocedimento
inicio
t1<- 0
escreval(t1)
t2<-1
escreval(t2)
para c:= 3 ate 10 faca
 proximoFibonacci(T1,T2)
 fimpara
fimalgoritmo
